version: '3'
services:
  C1:
    environment:
      - LISTENING_PORT=8080
      - SENDING_PORT=8080
      - OPERATING_MODE=2 # addition
      - SENDING_ADDRESS=C2
    image: myapp_image_tcp
    ports:
      - "9000:8080"
  C2:
    environment:
      - LISTENING_PORT=8080
      - SENDING_PORT=8080
      - OPERATING_MODE=0 # bitshift to the left
      - SENDING_ADDRESS=C3
    image: myapp_image_tcp
  C3:
    environment:
      - LISTENING_PORT=8080
      - SENDING_PORT=9001
      - OPERATING_MODE=3 # subtraction
      - SENDING_ADDRESS=192.168.64.1
    image: myapp_image_tcp

# To send: socat - TCP4:localhost:9000
# To receive: socat -v TCP-LISTEN:9001,reuseaddr STDOUT